### ISSUE TITLE
Misleading exception traces 

### ISSUE THREAD

**Issue by nknapp** [verbose/verb#64] opened 2015-05-25 21:15 UTC
When I was trying to create my [helpers for bootprint](https://github.com/nknapp/bootprint-verb-helpers), I had the problem that exceptions thrown in my helpers would seemingly show up as error in a completely different place. I've created the repository [verb-tests](https://github.com/nknapp/verb-tests) to illustrate: 

* In [the verbfile](https://github.com/nknapp/verb-tests/blob/master/verbfile.js#L5) I create an `exception()`-helper that throws an exception
* In [.verb.md](https://raw.githubusercontent.com/nknapp/verb-tests/master/.verb.md), I use this helper.

The output of `verb` (0.7.4 with cli 0.6.2) is: 

```
[23:09:32] using verbfile ~/privat/node-libraries/verb-tests/verbfile.js
[23:09:32] starting 'default'
[23:09:32] finished 'default' after 12 ms
async-helper-base: {%= badge("coverage") %} error: %j Error: Intended exception for testing
```
It suggests the error is thrown in `badge("coverage")` althout it was clearly thrown in `exception()`.
Also, without stack-traces, it can be rather time-consuming to find the bugs in my own helpers.

**Comment by jonschlinkert** [comment] 2015-05-25 21:32
agreed, @doowb and I have been talking about this a lot. I'm very open to suggestions for better error handling. If we can agree on a solid strategy and conventions for error reporting on helpers, plugins and middleware, I would be happy to implement them across our projects.

**Comment by nknapp** [comment] 2015-05-25 22:22
I corrected the above link to the helpers-project. 

>  I would be happy to implement them across our projects.

Just in order to avoid misunderstandings. I just want to use `verb` to document 
my project. My project (`Bootprint`) does not use `verb` or build upon, so we don't need to implement anything across verb and my project, if that's what you meant. (Well, OK, the project `bootprint-verb-helper` does use verb, but it only defines helpers for use in `.verb.md`).

>  I'm very open to suggestions for better error handling. 

For me, it would suffice to have a stack-trace printed to the console when an error in a helper occurs. Really, the only problem is that it is unclear where the error really occured.
Same for errors in the template itself. Change the `.verb.md` in `verb-test` to 

```
# {%= name %} {%= badge("fury") %} {%= badge("travis") %} {%= badge("coverage") %}

> {%= description %}

## Example

{%= exception() }

## License
{%= copyright({start: 2015}) %}
{%= license() %}
```
(do you spot the error), and you get the output 

```
SyntaxError: Unexpected token }
[TypeError: engine-cache `render` expects a string or function.]
[TypeError: undefined is not a function]
[TypeError: undefined is not a function]
[TypeError: undefined is not a function]
/home/nknappmeier/privat/node-libraries/verb-tests/node_modules/verb/node_modules/session-cache/node_modules/continuation-local-storage/context.js:78
      throw exception;
            ^
TypeError: undefined is not a function
    at DestroyableTransform._transform (/home/nknappmeier/privat/node-libraries/verb-tests/node_modules/verb/lib/plugins/dest.js:44:26)
    at DestroyableTransform.Transform._read (/home/nknappmeier/privat/node-libraries/verb-tests/node_modules/verb/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/nknappmeier/privat/node-libraries/verb-tests/node_modules/verb/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/nknappmeier/privat/node-libraries/verb-tests/node_modules/verb/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/nknappmeier/privat/node-libraries/verb-tests/node_modules/verb/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/home/nknappmeier/privat/node-libraries/verb-tests/node_modules/verb/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Stream.method [as write] (/home/nknappmeier/privat/node-libraries/verb-tests/node_modules/verb/node_modules/event-stream/node_modules/duplexer/index.js:47:39)
    at Stream.ondata (stream.js:51:26)
    at Stream.<anonymous> (/home/nknappmeier/privat/node-libraries/verb-tests/node_modules/verb/node_modules/session-cache/node_modules/continuation-local-storage/context.js:74:17)
    at Stream.emit (events.js:107:17)
```
In such a case (template parsing errors), it would be nice to just have an output like
```
SyntaxError: Unexpected token } in line 7:<insert row number here>
``` 
instead of having all follow-up errors and the stack-trace in the log.
I'm not sure what you mean by "strategy and conventions". Logging to the console is fine for me (at the moment).

**Comment by jonschlinkert** [comment] 2015-05-25 22:38
> Just in order to avoid misunderstandings.... I'm not sure what you mean by "strategy and conventions".

no misunderstandings, perhaps it's easier to explain this way. Can you show me where in the codebase we would "log those errors to the console"? somewhere errors aren't being bubbled up, or we're not even catching them in the first place.

**Comment by jonschlinkert** [comment] 2015-05-25 22:39
fwiw @doowb and I discussed that session-cache might be the cause, but I don't think anything has been done about it yet...

**Comment by jonschlinkert** [comment] 2015-05-26 04:26
@nknapp please try the latest release and let me know if anything has improved. I completely removed session-cache and made sure that all internal plugins catch errors

**Comment by nknapp** [comment] 2015-05-26 06:53
> no misunderstandings, perhaps it's easier to explain this way. Can you show me where in the codebase we would "log those errors to the console"? somewhere errors aren't being bubbled up, or we're not even catching them in the first place.

I'll have a look tonight (CEST). I wish I had more time to work on such things.

**Comment by nknapp** [comment] 2015-05-26 20:27
Mhm, I get an exception: At [verb/lib/transforms/init/load.js:29:12](https://github.com/verbose/verb/blob/master/lib/transforms/init/load.js#L24), `app.config.get('templates');` seems to resolve to `undefined`. In the debugger, the `data-store` in app.config seems to point to `~/data-store`, only this directory does not exist. Could that be the problem?

**Comment by jonschlinkert** [comment] 2015-05-28 02:22
> seems to point to ~/data-store, only this directory does not exist. Could that be the problem?

Hmmm, yes. that might be the problem. what OS are you on?

**Comment by tunnckoCore** [comment] 2015-05-28 02:42
btw, I also noticed it today. shouldn't it be hidden? `~/.data-store` better?

**Comment by jonschlinkert** [comment] 2015-05-28 03:29
yeah, agreed.. I thought it was... I'm looking into it

**Comment by jonschlinkert** [comment] 2015-05-28 03:33
nvm, it's not a regression, I just remembered `~/data-store/` is the directory. here is where I removed the dot: https://github.com/jonschlinkert/data-store/commit/059bb8cda4ad3c370080716c48df71d0b2da7ea9#diff-168726dbe96b3ce427e7fedce31bb0bcL37. 

still looking into why it's not resolving for you

**Comment by nknapp** [comment] 2015-05-28 06:51
> Hmmm, yes. that might be the problem. what OS are you on?

Ubuntu 14.04 (Lubuntu, actually).

**Comment by nknapp** [comment] 2015-05-28 06:52
@jonschlinkert  do you *have* a `~/data-store/`directory? have you created it manually?

**Comment by jonschlinkert** [comment] 2015-05-28 10:16
> have you created it manually?

No, it's [created when the object is saved](https://github.com/jonschlinkert/data-store/blob/master/index.js#L277)

**Comment by nknapp** [comment] 2015-05-28 11:36
ok, the problem is probably, that, if it doesn't exist, `app.config` is simply an empty store. Maybe `verb` tries to read it before writing, but there is just nothing to read. (I've seen in the debugger, that the Store is empty.)

**Comment by nknapp** [comment] 2015-05-30 23:16
With issue #62 resolved, I could test the stack-trace issue and I get different results than in verb 0.7.4.
I've updated the [verb-tests](https://github.com/nknapp/verb-tests) repository so that `.verb.md` only contains the helper that throws an exception. Verb's output ends with 
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
true
```
and no other signs of an errors are displayed.
I think one reason is that in [async-helpers/index.js, line 262](https://github.com/doowb/async-helpers/blob/master/index.js#L262), exception are ignored and not forwarded to the `next()`-function.
But fixing this is not enough. If the error is forwarded to the next-function, it reaches [the verb-render-plugin](https://github.com/verbose/verb/blob/master/lib/plugins/render.js#L31), but is still no stack-trace is displayed.

**Comment by jonschlinkert** [comment] 2015-05-31 18:06
@nknapp was this resolved with the async-helpers pr?

thanks so much for all of the help!

**Comment by nknapp** [comment] 2015-05-31 19:19
With the async-helpers pr, it is now possible to log stack-traces by adding an on-error-handler to the stream as in:
```js
verb.task('default', function () {
  verb.src(['.verb.md'])
    .pipe(verb.dest('./'))
    .on("error", function(err) {
      console.log(err.stack);
    });
}}
```
Maybe this should be documented, or a default error-handler should be added to `verb.dest()`.
 
Apart from that, I'm still debugging through the rendering process, trying to figure out, if lodash can enrich syntax-errors in the template with line-numbers or such. That would be really cool. But I can also open another issue for that, once I've come far enough.

**Comment by jonschlinkert** [comment] 2015-05-31 20:42
> t is now possible to log stack-traces by adding an on-error-handler to the stream as in:

Okay, I'm going to close this then so we can open new issues for anything related - to keep them as specific as possible. 

> Maybe this should be documented

Noted, I'll make sure to add something

> if lodash can enrich syntax-errors in the template with line-numbers or such.

[like this](https://github.com/jonschlinkert/rethrow#rethrow-)? :)

**Comment by jonschlinkert** [comment] 2015-05-31 20:42
and thanks again for your help @nknapp!

**Closed by jonschlinkert** 2015-05-31 20:42 UTC

**Comment by nknapp** [comment] 2015-06-01 00:21
> like this? :)

:smirk: kind of, but not so much the library, more the example.

> and thanks again for your help @nknapp!

No problem. Digging through the code was quite fun, actually. And before I start and make my own library for the same use-case, it's certainly better to remove the obstacles in an existing one.
I think the main problem with npm is, that there are too many libraries that actually do the same, just a little different.
And I would actually like to thank you for taking the time to discuss my issues.

**Comment by nknapp** [comment] 2015-06-05 06:56
> > if lodash can enrich syntax-errors in the template with line-numbers or such.

> like this? :)

[Like this!](https://www.npmjs.com/package/lodash-template-validator)

**Comment by jonschlinkert** [comment] 2015-06-05 09:03
Have you tested that with loops or more complicated expressions e.g. what if the error is inside a for loop? e.g. does this do something my example doesn't do? It would be pretty easy to get column by splitting characters too. just trying see what the advantage is (or rather, if the advantage is worth the amount of additional code), since https://github.com/jonschlinkert/rethrow already works as well as I would expect. and the line number is pretty easy to get.

**Comment by nknapp** [comment] 2015-06-05 19:46
Templates as in the `comment-patterns` module (`.docs/languages.md`) which span evals across multiple lines, shouldn't work correctly with the 'rethrow` example: 

```
{% _.forEach(langDB, function(lang) { %}
### {%= lang.name %}
{%= literal(lang) %}
{% }) %}
```
The `rethrow`-example is splitting the template into lines and evaluating each line as complete template. If multiple lines of the template are needed to form a correct template, the code will throw errors for correct templates. If the actual error is further down, it won't be noticed and the wrong location will be displayed.
That's why I tried to find a way to locate the errors without splitting the template.
