### ISSUE TITLE
Which version/package should I use as of late 2015 early 2016?

### ISSUE THREAD

**Issue by tunnckoCore** [verbose/verb#84] opened 2016-01-29 20:00 UTC
How and what to install to get latest? Should i install `verb` globally or `verb-cli`? - i cant remember what was finally.

**Comment by tunnckoCore** [comment] 2016-01-29 20:18
Ooh, ookey, I just forgot lol. That 3+ month not work... :D 

```
npm i -g git://github.com/verbose/verb.git#dev
```

**Comment by tunnckoCore** [comment] 2016-01-29 20:23
OKey, installed, what next? Any verb command or option fails
- any of `verb init`, `verb help`, `verb --help`, `verb [-v|--version]`

with that:

```
[charlike@voltaire dev]$ verb init
/usr/local/lib/node_modules/verb/node_modules/helper-reflinks/index.js:39
    cache.keys = utils.keys(cache.pkg.dependencies || {});
                                     ^

TypeError: Cannot read property 'dependencies' of null
    at Function.module.exports (/usr/local/lib/node_modules/verb/node_modules/helper-reflinks/index.js:39:38)
    at module.exports (/usr/local/lib/node_modules/verb/lib/runner/helpers.js:135:38)
    at module.exports (/usr/local/lib/node_modules/verb/lib/runner/defaults.js:8:3)
    at Object.preload (/usr/local/lib/node_modules/verb/lib/runner/preload.js:14:3)
    at Verb.<anonymous> (/usr/local/lib/node_modules/verb/node_modules/base-runner/index.js:485:21)
    at Verb.initVerb (/usr/local/lib/node_modules/verb/index.js:81:15)
    at new Verb (/usr/local/lib/node_modules/verb/index.js:59:10)
    at getConfig (/usr/local/lib/node_modules/verb/node_modules/base-runner/index.js:497:17)
    at getConfig (/usr/local/lib/node_modules/verb/node_modules/base-runner/index.js:515:12)
    at Function.Ctor.getConfig (/usr/local/lib/node_modules/verb/node_modules/base-runner/index.js:104:18)

```

**Comment by tunnckoCore** [comment] 2016-01-29 20:26
And okey, when have package.json in cwd it again fails

```
[charlike@voltaire test-verb]$ verb help
module.js:341
    throw err;
    ^

Error: Cannot find module '../../templates/includes'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at module.exports (/usr/local/lib/node_modules/verb/lib/runner/templates.js:10:18)
    at Object.preload (/usr/local/lib/node_modules/verb/lib/runner/preload.js:15:3)
    at Verb.<anonymous> (/usr/local/lib/node_modules/verb/node_modules/base-runner/index.js:485:21)
    at Verb.initVerb (/usr/local/lib/node_modules/verb/index.js:81:15)
    at new Verb (/usr/local/lib/node_modules/verb/index.js:59:10)
    at getConfig (/usr/local/lib/node_modules/verb/node_modules/base-runner/index.js:497:17)
[charlike@voltaire test-verb]$
```

**Comment by tunnckoCore** [comment] 2016-02-04 02:08
:100: bump?

**Comment by jonschlinkert** [comment] 2016-02-04 02:40
I'm very close to releasing a new and improved verb, that will be much faster, easier to use etc. I'd rather just get that done first, then I'll ping you as soon as I push up.

**Comment by Melindrea** [comment] 2016-02-04 22:00
Ooh, I will be joining this thread then. I haven't used READMEs in ages, but verb rocks

**Comment by jonschlinkert** [comment] 2016-02-04 22:03
thank you!!! that's so nice of you to say. If you were able to see through verb's warts enough to like it before, I can't wait to show you the new and improved verb :)

**Comment by tunnckoCore** [comment] 2016-02-05 02:08
Great! I can't wait to see your most awesome thing. My is the "Hybrids", upcoming book "Javascript Hybrids" and (at all) whole https://github.com/hybridables stack. I hope i can finalize all of them in next month or two. lol

Cheers,
Charlike!

**Comment by jonschlinkert** [comment] 2016-02-05 05:21
hey that's great @tunnckoCore! it's important to have big goals!

**Comment by jonschlinkert** [comment] 2016-02-06 10:15
fun fact: verb v0.9.0 has 1092 unit tests lol.

**Comment by tunnckoCore** [comment] 2016-02-06 14:44
haha, yea, it's normal. I have same situation around hybrids - not with so big number, but again. And i'm starting to think that they all not always needed fully.
I'm always for "the more the better" which i call "200% coverage before stable release (in my case before v1 - i dont stay on >v1)", but it's not needed to copy-paste from (for example) assemble-core, templates, template and etc, LOL.

But yea, great job.

**Comment by jonschlinkert** [comment] 2016-02-06 15:19
> but it's not needed to copy-paste from (for example) assemble-core, templates, template and etc

it is actually! ;) until we release a test suite, we need to have complete integration and regression tests on all of the inheriting libraries. It prevents bugs often! Many times I've updated the tests and was reminded of a small difference in the libs... anyway, I automate everything, so there IMHO there can never be too many unit tests!

**Comment by tunnckoCore** [comment] 2016-02-07 04:05
> It prevents bugs often! Many times I've updated the tests and was reminded of a small difference in the libs...

Absolutely! That's why I always think (in background, lol) for new and new cases and write new and new tests.

**Comment by jonschlinkert** [comment] 2016-02-12 22:56
ok closing this since I think the question was answered, and we're about to release 0.9

**Closed by jonschlinkert** 2016-02-12 22:56 UTC
